const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY="festivalCards";let people=JSON.parse(localStorage.getItem(KEY)||"[]"),selected=new Set(),editingId=null;
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.remove("show"),1800)}
function hobby(v=""){if($$("#hobbyInputs input").length>=6)return toast("趣味は6個まで");let d=document.createElement("div");d.className="hobby";d.innerHTML=`<input value="${v}" placeholder="例：ゲーム"><button>×</button>`;d.querySelector("input").oninput=()=>{autoHash();update()};d.querySelector("button").onclick=()=>{d.remove();autoHash();update()};$("#hobbyInputs").append(d);updateCount()}
function hobbies(){return $$("#hobbyInputs input").map(x=>x.value.trim()).filter(Boolean)}function updateCount(){$("#hobbyCount").textContent=`${hobbies().length} / 6`}
function autoHash(){if(document.activeElement!==$("#hashtags"))$("#hashtags").value=hobbies().map(x=>"#"+x.replace(/\s/g,"")).join(" ")}
function data(){return{id:editingId||crypto.randomUUID(),name:$("#name").value.trim(),className:$("#className").value.trim(),nickname:$("#nickname").value.trim(),hobbies:hobbies(),secretSkill:$("#secretSkill").value.trim(),theme:$("#theme").value,orientation:$("#orientation").value,hashtags:$("#hashtags").value.trim(),updatedAt:Date.now()}}
function update(){let d=data();$("#previewName").textContent=d.name||"名前未入力";$("#previewClass").textContent=d.className||"クラス";$("#previewNickname").textContent=d.nickname||"nickname";$("#previewHobbies").textContent=d.hashtags||(d.hobbies.length?d.hobbies.map(x=>"#"+x).join(" "):"#趣味");$("#previewSecret").textContent=d.secretSkill||"特技を入力";$("#printCard").className=`card theme-${d.theme} ${d.orientation}`;updateCount()}
function save(){let d=data();if(!d.name)return toast("人物の名前を入力してください");let i=people.findIndex(x=>x.id===d.id);i<0?people.unshift(d):people[i]=d;editingId=d.id;store();toast("保存しました")}
function store(){localStorage.setItem(KEY,JSON.stringify(people));render()}
function load(p){editingId=p.id;$("#name").value=p.name||"";$("#className").value=p.className||"";$("#nickname").value=p.nickname||"";$("#secretSkill").value=p.secretSkill||"";$("#theme").value=p.theme||"purple";$("#orientation").value=p.orientation||"landscape";$("#hashtags").value=p.hashtags||"";$("#hobbyInputs").innerHTML="";(p.hobbies?.length?p.hobbies:[""]).forEach(hobby);update();toast("読み込みました")}
function render(){let q=$("#search").value.toLowerCase(),a=people.filter(p=>[p.name,p.className,...(p.hobbies||[])].join(" ").toLowerCase().includes(q));if($("#sort").value==="name")a.sort((x,y)=>x.name.localeCompare(y.name,"ja"));else a.sort((x,y)=>y.updatedAt-x.updatedAt);$("#peopleCount").textContent=people.length+"人";$("#selectedCount").textContent=selected.size+"人選択中";let box=$("#peopleList");box.innerHTML="";a.forEach(p=>{let e=document.createElement("div");e.className="person";e.innerHTML=`<input type="checkbox" ${selected.has(p.id)?"checked":""}><div><strong>${p.name}</strong><small>${p.className||"クラス未入力"} / ${(p.hobbies||[]).slice(0,2).join("・")}</small></div><button>×</button>`;e.querySelector("input").onclick=z=>{z.stopPropagation();z.target.checked?selected.add(p.id):selected.delete(p.id);render()};e.querySelector("button").onclick=z=>{z.stopPropagation();people=people.filter(x=>x.id!==p.id);selected.delete(p.id);store()};e.onclick=()=>load(p);box.append(e)})}
$("#addHobby").onclick=()=>hobby();$("#saveBtn").onclick=save;$("#newBtn").onclick=()=>{editingId=null;["name","className","nickname","secretSkill","hashtags"].forEach(x=>$("#"+x).value="");$("#hobbyInputs").innerHTML="";hobby();update()};["name","className","nickname","secretSkill","hashtags"].forEach(x=>$("#"+x).oninput=update);$("#theme").onchange=update;$("#orientation").onchange=update;$("#search").oninput=render;$("#sort").onchange=render;$("#selectAllBtn").onclick=()=>{let ids=people.map(x=>x.id),all=ids.every(x=>selected.has(x));ids.forEach(x=>all?selected.delete(x):selected.add(x));render()};$("#deleteSelectedBtn").onclick=()=>{people=people.filter(x=>!selected.has(x.id));selected.clear();store()};$("#deleteAllBtn").onclick=()=>{if(confirm("全削除しますか？")){people=[];selected.clear();store()}};
$("#pngBtn").onclick=async()=>{try{let c=await html2canvas($("#printCard"),{scale:3});let a=document.createElement("a");a.download=($("#name").value||"participant")+".png";a.href=c.toDataURL();a.click();toast("PNGを出力しました")}catch(e){toast("PNG出力に失敗しました")}};
$("#printBtn").onclick=()=>{let portrait=$("#orientation").value==="portrait",st=document.getElementById("ps")||document.head.appendChild(Object.assign(document.createElement("style"),{id:"ps"}));st.textContent=portrait?'@page{size:A5 portrait;margin:0}@media print{.card{width:148mm!important;height:210mm!important}}':'@page{size:A5 landscape;margin:0}@media print{.card{width:210mm!important;height:148mm!important}}';setTimeout(()=>print(),50)};
hobby();update();render();